### ISSUE TITLE
Unable to run example.py

### ISSUE THREAD

**Issue by openSourceBugs** [ArduCAM/PCA9685#8]
./arduenv/bin/python3 ./example/Jetson/ServoKitExample.py
Traceback (most recent call last):
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/./example/Jetson/ServoKitExample.py", line 184, in <module>
    main()
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/./example/Jetson/ServoKitExample.py", line 180, in main
    curses.wrapper(draw_menu, None)
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/./example/Jetson/ServoKitExample.py", line 134, in draw_menu
    servoKit = ServoKit(4)
               ^^^^^^^^^^^
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/example/Jetson/ServoKit.py", line 33, in __init__
    self.kit = adafruit_servokit.ServoKit(channels=16)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/arduenv/lib/python3.11/site-packages/adafruit_servokit.py", line 88, in __init__
    i2c = board.I2C()
          ^^^^^^^^^^^
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/arduenv/lib/python3.11/site-packages/board.py", line 409, in I2C
    return busio.I2C(SCL, SDA)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/arduenv/lib/python3.11/site-packages/busio.py", line 37, in __init__
    self.init(scl, sda, frequency)
  File "/home/drone-project/articulated_robotics/ptz_camer_drivers_older/PCA9685/arduenv/lib/python3.11/site-packages/busio.py", line 162, in init
    raise ValueError(
ValueError: No Hardware I2C on (scl,sda)=(3, 2)
Valid I2C ports: ((1, 3, 2), (0, 1, 0), (10, 45, 44))

Also, is this for Jetson only?  I set this up under the impression that Raspberry Pi 4 buster was supported.

**Comment by openSourceBugs** [comment]
i'm checking the jump wires and double checked them and they are connected according to the diagram in the documentation sent with the camera.

**Comment by openSourceBugs** [comment]
the ./runServoDemo does seem to work.
